-- Add missing columns to jobs table
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS failure_count INTEGER DEFAULT 0;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS suggested_fixes TEXT;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS asset_id TEXT;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS client_id TEXT;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS vault_path TEXT;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 1;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS retry_after TIMESTAMPTZ;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMPTZ;
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS worker_id TEXT;
