#!/bin/bash
# Quick launcher for 3-program batch test

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║                    3-PROGRAM BATCH TEST MONITOR                            ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "This monitor will:"
echo "  ✅ Wait for you to drop 3 video files"
echo "  ✅ Track them through the entire pipeline"
echo "  ✅ Measure performance and bottlenecks"
echo "  ✅ Generate a comprehensive report"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "INSTRUCTIONS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. This terminal will start the monitor"
echo "2. Open ANOTHER terminal and copy your 3 video files to:"
echo "   1_INBOX/01_AUTO_PILOT/Classic/"
echo ""
echo "   Example:"
echo "   cp ~/your/program1.mp4 1_INBOX/01_AUTO_PILOT/Classic/"
echo "   cp ~/your/program2.mp4 1_INBOX/01_AUTO_PILOT/Classic/"
echo "   cp ~/your/program3.mp4 1_INBOX/01_AUTO_PILOT/Classic/"
echo ""
echo "3. Walk away! The monitor will track everything."
echo "4. When done, check: reports/batch_report_*.txt"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Ready to start? Press ENTER to begin monitoring..."
echo ""

# Start the monitor
python3 utils/monitor_batch.py --watch-new 3 --interval 5 --max-hours 6

echo ""
echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║                           TEST COMPLETE!                                   ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📄 Check the report in: reports/"
ls -lt reports/batch_report_*.txt 2>/dev/null | head -1
echo ""
