-- Enable Row Level Security (good practice, though we use service_role to bypass initially)
-- Tables for Omega Workflow

-- 1. JOBS
CREATE TABLE IF NOT EXISTS public.jobs (
    file_stem TEXT PRIMARY KEY,
    stage TEXT,
    status TEXT,
    progress FLOAT8,
    updated_at TIMESTAMPTZ,
    meta JSONB,
    target_language TEXT DEFAULT 'is',
    program_profile TEXT DEFAULT 'standard',
    subtitle_style TEXT DEFAULT 'Classic',
    editor_report TEXT,
    client TEXT DEFAULT 'unknown',
    due_date DATE
);

-- 2. DELIVERIES
CREATE TABLE IF NOT EXISTS public.deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_stem TEXT,
    client TEXT,
    delivered_at TIMESTAMPTZ,
    method TEXT,
    notes TEXT
);

-- 3. PROGRAMS
CREATE TABLE IF NOT EXISTS public.programs (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    original_filename TEXT,
    video_path TEXT,
    thumbnail_path TEXT,
    duration_seconds FLOAT8,
    client TEXT,
    due_date TEXT,
    default_style TEXT DEFAULT 'Classic',
    status TEXT DEFAULT 'ACTIVE',
    deleted_at TIMESTAMPTZ,
    deleted_original_filename TEXT,
    deleted_video_path TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    meta JSONB
);

-- 4. MASTER SCRIPTS
CREATE TABLE IF NOT EXISTS public.master_scripts (
    id TEXT PRIMARY KEY,
    program_id TEXT NOT NULL REFERENCES public.programs(id),
    language_code TEXT NOT NULL,
    language_name TEXT,
    state TEXT DEFAULT 'draft',
    version INTEGER DEFAULT 1,
    locked_at TIMESTAMPTZ,
    locked_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    meta JSONB,
    UNIQUE(program_id, language_code)
);

-- 5. TRACKS
CREATE TABLE IF NOT EXISTS public.tracks (
    id TEXT PRIMARY KEY,
    program_id TEXT NOT NULL REFERENCES public.programs(id),
    type TEXT NOT NULL DEFAULT 'subtitle',
    language_code TEXT NOT NULL,
    language_name TEXT,
    stage TEXT DEFAULT 'QUEUED',
    state TEXT DEFAULT 'draft',
    status TEXT DEFAULT 'Pending',
    progress FLOAT8 DEFAULT 0.0,
    delivery_status TEXT DEFAULT 'PENDING',
    job_id TEXT,
    voice_id TEXT,
    rating FLOAT8,
    output_path TEXT,
    depends_on TEXT REFERENCES public.tracks(id),
    master_script_id TEXT REFERENCES public.master_scripts(id),
    output_version TEXT DEFAULT '1.0',
    output_override BOOLEAN DEFAULT FALSE,
    override_reason TEXT,
    override_author TEXT,
    override_timestamp TIMESTAMPTZ,
    pending_resync BOOLEAN DEFAULT FALSE,
    locked_at TIMESTAMPTZ,
    locked_by TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    meta JSONB
);

-- 6. TRACK DELIVERIES
CREATE TABLE IF NOT EXISTS public.track_deliveries (
    id TEXT PRIMARY KEY,
    track_id TEXT NOT NULL REFERENCES public.tracks(id),
    destination TEXT,
    recipient TEXT,
    delivered_at TIMESTAMPTZ DEFAULT NOW(),
    notes TEXT
);

-- 7. SCRIPT EDITS
CREATE TABLE IF NOT EXISTS public.script_edits (
    id TEXT PRIMARY KEY,
    master_script_id TEXT NOT NULL REFERENCES public.master_scripts(id),
    track_id TEXT REFERENCES public.tracks(id),
    change_type TEXT NOT NULL,
    summary TEXT,
    author TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    meta JSONB
);

-- 8. SYSTEM STATE
CREATE TABLE IF NOT EXISTS public.system_state (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_tracks_program ON public.tracks(program_id);
CREATE INDEX IF NOT EXISTS idx_tracks_stage ON public.tracks(stage);
CREATE INDEX IF NOT EXISTS idx_programs_client ON public.programs(client);
CREATE INDEX IF NOT EXISTS idx_script_edits_master ON public.script_edits(master_script_id);
